pipeline:
  name: Build spooky
  identifier: Build_inaki_ortizdelandaluce_spooky_1728293742969
  projectIdentifier: Labs
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        delegateSelectors:
          - docker-delegate
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: inaki-ortizdelandaluce/spooky
        build: <+input>
